### ISSUE TITLE
Failed to generate report due to schema namespace problem

### ISSUE THREAD

**Issue by mnorton** [mulesoft/mule-migration-assistant#423]
$ java -jar mule-migration-assistant-runner-*1.0.0.jar -projectBasePath ../question-sys-api -destinationProjectBasePath ../questions-sys-api-v4 -muleVersion 4.3.0 -parentDomainBasePath ../ms3-domain
Executing migrator 1.0.0...
===============================================================================
MIGRATION FAILED
===============================================================================
Total time: 2.444 s
Exception: $s
 Failed to generate report.
com.mulesoft.tools.migration.engine.exception.MigrationJobException: $s
 Failed to generate report.
        at com.mulesoft.tools.migration.engine.MigrationJob.generateReport(MigrationJob.java:170)
        at com.mulesoft.tools.migration.engine.MigrationJob.execute(MigrationJob.java:103)
        at com.mulesoft.tools.migration.MigrationRunner.main(MigrationRunner.java:82)
Caused by: com.mulesoft.tools.migration.engine.exception.MigrationJobException: $s
 Failed to obtain new element location.
        at com.mulesoft.tools.migration.report.html.model.ReportEntryModel.setElementLocation(ReportEntryModel.java:90)
        at com.mulesoft.tools.migration.engine.MigrationJob.generateReport(MigrationJob.java:168)
        ... 2 more
Caused by: java.lang.IllegalArgumentException: **The default (no prefix) Namespace URI for XPath queries is always '' and it cannot be redefined to 'http://www.mulesoft.org/schema/mule/core'.**
        at org.jdom2.xpath.util.AbstractXPathCompiled.<init>(AbstractXPathCompiled.java:144)
        at org.jdom2.xpath.jaxen.JaxenCompiled.<init>(JaxenCompiled.java:148)
        at org.jdom2.xpath.jaxen.JaxenXPathFactory.compile(JaxenXPathFactory.java:82)
        at org.jdom2.xpath.XPathFactory.compile(XPathFactory.java:261)
        at com.mulesoft.tools.migration.report.html.model.ReportEntryModel.setElementLocation(ReportEntryModel.java:117)
        at com.mulesoft.tools.migration.report.html.model.ReportEntryModel.setElementLocation(ReportEntryModel.java:87)
        ... 3 more

===============================================================================

**Comment by mnorton** [comment]
As an afterthought, this happened in the downloaded "compiled" version of the app.  Not the current sources.

**Comment by mnorton** [comment]
Just to be sure, I cloned the source code (mule-migration-assistant-runner-1.0.1-SNAPSHOT.jar), built it locally using Maven and ran it with the same parameters.  I get the same error response.  It's possible that one of the XML files in my project are not correctly define w.r.t XML namespaces.  If so, I would expect a better error message than the stack dump provides.

**Comment by dasrajib** [comment]
I am facing same xml name space issue for any mule API in 3.x I tried. Do you know the solution?

**Comment by mnorton** [comment]
I have a couple of theories, @dasrajib .

1.  It's possible that the namespace declarations in one of my files is wrong or slightly off.  Since it runs just fine in Mule 3.8.3, it may mean that a more modern version of XML parse utilities are being more strict and the exception is not caught.

2.  My project had a reference to a domain.  It was a very simple domain, only a few external properties, but domains were different back then.

Meanwhile, I've tried the MMA on other (even simpler) projects and it has worked just fine.

- Mark

**Comment by dasrajib** [comment]
I removed domain project and deleted target folder, + our exception handling jar from mule 3. After that this MMA is successfully converting from mule 3 to mule 4 almost 80%. This is great to start with.

**Comment by mnorton** [comment]
Unfortunately, the Mule 3 application that caused this problem is proprietary and cannot be shared on a public net like this one.  While it would be nice if the MMA was improved to handle this sort of situation, it is about six months too late for me.  My team and I just completed a migration of 30 Mule 3 apps to Mule 4.  Since the MMA was buggy, we didn't use it.

**Comment by afelisatti** [comment]
Hi, @mnorton. We understand. It's a shame the project did not help your migration process. We are trying to crack down on these bugs and react to user feedback quicker from now on. 
As for this bug in particular,  thanks for the report and insights. We'll review @ceazy79's commit referenced above, which seems to point at a namespace issue.

**Comment by ceazy79** [comment]
Hoping that it might help to resolve the issue: the bug can be reproduced with a very simple demo project:
[example-project.zip](https://github.com/mulesoft/mule-migration-assistant/files/6908182/example-project.zip)
Like Mark we already finished our migration but maybe it can be fixed for others that run into the same problem.

**Comment by afelisatti** [comment]
Thanks, @ceazy79! That is very helpful!
