### ISSUE TITLE
Trying to use the tool to migration from 3.9.2 to 4.x and getting the NullPointerException.

### ISSUE THREAD

**Issue by manojtrek** [mulesoft/mule-migration-assistant#458]
Caused by: java.lang.NullPointerException
        at com.mulesoft.tools.migration.library.mule.steps.pom.RemoveMuleAppMavenPlugin.lambda$execute$3(RemoveMuleAppMavenPlugin.java:33) ~[mule-migration-tool-library-1.0.1-SNAPSHOT.jar:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:1.8.0_281]
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:1.8.0_281]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_281]
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_281]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_281]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:1.8.0_281]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:1.8.0_281]
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_281]
        at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:1.8.0_281]
        at com.mulesoft.tools.migration.library.mule.steps.pom.RemoveMuleAppMavenPlugin.execute(RemoveMuleAppMavenPlugin.java:32) ~[mule-migration-tool-library-1.0.1-SNAPSHOT.jar:?]
        at com.mulesoft.tools.migration.library.mule.steps.pom.RemoveMuleAppMavenPlugin.execute(RemoveMuleAppMavenPlugin.java:20) ~[mule-migration-tool-library-1.0.1-SNAPSHOT.jar:?]
        at com.mulesoft.tools.migration.task.AbstractMigrationTask.lambda$execute$5(AbstractMigrationTask.java:86) ~[mule-migration-tool-api-1.0.1-SNAPSHOT.jar:?]
        at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_281]
        at com.mulesoft.tools.migration.task.AbstractMigrationTask.execute(AbstractMigrationTask.java:84) ~[mule-migration-tool-api-1.0.1-SNAPSHOT.jar:?]

**Comment by holiday-sunrise** [comment]
Can you add your pom.xml

**Comment by holiday-sunrise** [comment]
Fixed ?

**Comment by manojtrek** [comment]
Seems like issue with profiles, Excluding those prior to migration helped resolved the issue, will create a PR.
