### ISSUE TITLE
GC overhead limit exceeded

### ISSUE THREAD

**Issue by bharathnj** [mulesoft/mule-migration-assistant#691]
**Version used**
MMA version : 1.4.0-alpha

**Describe the bug**
Getting GC overhead limit exceeded error

**Relevant logs**
C:\Users\test\Downloads\mule-migration-assistant-runner-1.4.0-alpha>java -jar mule-migration-assistant-runner-1.4.0-alpha.jar -muleVersion 4.3.0 -projectBasePath "C:\Users\test\AnypointStudio\workspace3\test-documents-service" -destinationProjectBasePath "C:\Users\test\Desktop\mma-test"
Executing migrator 1.4.0-alpha...
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
        at org.jdom2.AttributeList.ensureCapacity(AttributeList.java:363)
        at org.jdom2.AttributeList.add(AttributeList.java:156)
        at org.jdom2.Element.setAttribute(Element.java:1334)
        at org.jdom2.DefaultJDOMFactory.setAttribute(DefaultJDOMFactory.java:318)
        at org.jdom2.input.sax.SAXHandler.startElement(SAXHandler.java:721)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
        at org.jdom2.input.sax.SAXBuilderEngine.build(SAXBuilderEngine.java:217)
        at org.jdom2.input.sax.SAXBuilderEngine.build(SAXBuilderEngine.java:277)
        at org.jdom2.input.sax.SAXBuilderEngine.build(SAXBuilderEngine.java:264)
        at org.jdom2.input.SAXBuilder.build(SAXBuilder.java:1116)
        at com.mulesoft.tools.migration.step.util.XmlDslUtils.generateDocument(XmlDslUtils.java:709)
        at com.mulesoft.tools.migration.project.model.ApplicationModel$ApplicationModelBuilder.build(ApplicationModel.java:679)
        at com.mulesoft.tools.migration.engine.MigrationJob.generateTargetApplicationModel(MigrationJob.java:216)
        at com.mulesoft.tools.migration.engine.MigrationJob.execute(MigrationJob.java:132)
        at com.mulesoft.tools.migration.MigrationRunner.run(MigrationRunner.java:86)
        at com.mulesoft.tools.migration.MigrationRunner.main(MigrationRunner.java:71)

**Comment by bharathnj** [comment]
worked in another system.
